name: Sync Debian Branches

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  sync-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: src

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          echo "::group::Install dependencies start."

          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          pip install GitPython

          echo "::endgroup::"

      - name: Run Python Sync
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          GITHUB_SHA: ${{ github.sha }}
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          wget https://raw.githubusercontent.com/qualcomm-qrb-ros/.github/sync_debian_branch/sync_debian_branches.py
          python3 sync_debian_branches.py --mode direct --path src